apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintrack-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fintrack-backend
  template:
    metadata:
      labels:
        app: fintrack-backend
    spec:
      containers:
      - name: fintrack-backend
        image: <registry>/fintrack-backend:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: fintrack-backend-service
spec:
  selector:
    app: fintrack-backend
  ports:
  - port: 80
    targetPort: 5000
  type: ClusterIP