apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintrack-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fintrack-frontend
  template:
    metadata:
      labels:
        app: fintrack-frontend
    spec:
      containers:
      - name: fintrack-frontend
        image: <registry>/fintrack-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "http://fintrack-backend-service"
---
apiVersion: v1
kind: Service
metadata:
  name: fintrack-frontend-service
spec:
  selector:
    app: fintrack-frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer